/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

// ============================================================================
// SpMM Tiling 结构体 - kernel 和 host 共用
// ============================================================================
//
// 纯 C/C++ 语法，不含 __aicore__、__gm__ 等 ASC 关键字。
// 对应 DESIGN.md §1.5 Buffer 规划 + §2.1 多核切分策略。
//
// 多核切分（DESIGN.md §2.1）：
//   - 沿 dst 行维度切分，每行独立计算归约
//   - blockDim = min(num_dst_nodes, coreNum)，Host 侧动态获取 Vector Core 数量
//   - 每核处理 [blockIdx * rowsPerCore, min((blockIdx+1) * rowsPerCore, num_dst_nodes))
//   - 尾核 indptr 越界读修复（WALKTHROUGH.md 问题1仲裁结论）：
//     尾核按 actualRows = num_dst_nodes - blockIdx * rowsPerCore 加载 indptr，
//     而非固定 (rowsPerCore + 1)。
//
// UB 切分（DESIGN.md §1.5、§2.2）：
//   - 逐行处理，邻居索引分批加载（每批 batchSize 个）
//   - batchSize 由 UB 剩余空间动态计算
//   - feat_dim ≤ 256 时整行加载，无需分 chunk
//   - UB 容量通过 Host 侧动态获取后传入
// ============================================================================

#pragma once

#include <cstdint>

// ============================================================================
// 常量定义
// ============================================================================

// UB 预留空间（用于栈帧等系统开销）
constexpr uint32_t UB_RESERVED = 2 * 1024;      // 预留 2 KB

// 批量邻居索引加载上限（DESIGN.md §1.5.2 MAX_BATCH，自设上限控制同步开销）
constexpr uint32_t MAX_BATCH = 4095;

// 数据类型标识
constexpr uint32_t DTYPE_FP32 = 0;
constexpr uint32_t DTYPE_FP16 = 1;

// reduce 操作标识
constexpr uint32_t REDUCE_SUM = 0;
constexpr uint32_t REDUCE_MAX = 1;
constexpr uint32_t REDUCE_MIN = 2;

// 32 字节对齐辅助（DESIGN.md §1.5 对齐计算）
constexpr uint32_t ALIGN_BYTES = 32;

// FP16 类型大小为 2 字节（host 侧不使用 half 类型，用 sizeof(int16_t) 替代）
constexpr uint32_t HALF_SIZE = 2;

// ============================================================================
// Tiling 数据结构 - 向核函数传递的运行时参数
// ============================================================================
struct SpmmTilingData {
    uint32_t numDstNodes;        // 目标节点数 = CSR 行数 = indptr 长度 - 1
    uint32_t numSrcNodes;        // 源节点数 = ufeat 行数
    uint32_t nnz;                // 非零元素总数 = 边数 = indices 长度 = indptr[num_dst_nodes]
    uint32_t featDim;            // 特征维度
    uint32_t blockDim;           // 实际使用的核数 = min(num_dst_nodes, coreNum)
    uint32_t rowsPerCore;        // 每核处理的行数 = ceil(num_dst_nodes / blockDim)
    uint32_t batchSize;          // UB 批量加载邻居索引数 B
    uint32_t dtype;              // 0=FP32, 1=FP16
    uint32_t reduceOp;           // 0=sum, 1=max, 2=min
    uint32_t featDimAlignedF;    // featDim 向上对齐到 32B（以 FP32 元素计，即 8 的倍数）
    uint32_t featDimAlignedH;    // featDim 向上对齐到 32B（以 FP16 元素计，即 16 的倍数）
    uint32_t ubSize;             // UB 容量（字节），Host 侧动态获取后传入
};
